### ISSUE TITLE
Error when running code

### ISSUE THREAD

**Issue by toastymp5** [mov-ebx/roblox-tracker#1]
Hey, I know nothing about coding Python, so this might be an error completely on my behalf.

When running the code, I got the error message below:

Traceback (most recent call last):
  File "C:\Users\User\Downloads\roblox-tracker-main\roblox-tracker-main\src\main.py", line 9, in <module>
    import requests, time
ModuleNotFoundError: No module named 'requests'

If you could help, that would be amazing!

**Comment by Powsu** [comment]
Traceback (most recent call last):
  File "rotracker-conor.py", line 14, in <module>
    last_online = track['LastOnline']
KeyError: 'LastOnline'

**Comment by ghost** [comment]
error Traceback (most recent call last):
  File main.py", line 14, in <module>
    last_online = track['LastOnline']
KeyError: 'LastOnline'

**Comment by mov-ebx** [comment]
My apologies for not responding for over a month, I forgot this project still existed.

toastymp5, for your problem, please install the requests library with the following command:
`pip install requests`

Powsu, and 1shotkillsniperstrikeshot, I'm gonna fix that issue soon. Thank you for alerting this to me.

**Comment by ghost** [comment]
alr thank you sir
